### ISSUE TITLE
error in heroku

### ISSUE THREAD

**Issue by Sasukezynho** [Alien-alfa/WhatsAppBot-MD#3]
2022-04-27T23:27:24.899394+00:00 app[worker.1]: 0|index  | ReferenceError: sessionName is not defined
2022-04-27T23:27:24.899404+00:00 app[worker.1]: 0|index  |     at Object.<anonymous> (/app/index.js:48:4224)
2022-04-27T23:27:24.899418+00:00 app[worker.1]: 0|index  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-04-27T23:27:24.899436+00:00 app[worker.1]: 0|index  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2022-04-27T23:27:24.899452+00:00 app[worker.1]: 0|index  |     at Module.load (node:internal/modules/cjs/loader:981:32)
2022-04-27T23:27:24.899469+00:00 app[worker.1]: 0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-27T23:27:24.899486+00:00 app[worker.1]: 0|index  |     at Object.<anonymous> (/app/.heroku/node/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-04-27T23:27:24.899502+00:00 app[worker.1]: 0|index  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-04-27T23:27:24.899518+00:00 app[worker.1]: 0|index  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2022-04-27T23:27:24.899535+00:00 app[worker.1]: 0|index  |     at Module.load (node:internal/modules/cjs/loader:981:32)
2022-04-27T23:27:24.899551+00:00 app[worker.1]: 0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-27T23:27:24.904088+00:00 app[worker.1]: PM2      | App [index:0] exited with code [1] via signal [SIGINT]
2022-04-27T23:27:24.904648+00:00 app[worker.1]: PM2      | Script /app/index.js had too many unstable restarts (16). Stopped. "errored"

**Comment by Sasukezynho** [comment]
help pls

**Comment by Alien-alfa** [comment]
ok let me see. I am working on updates. I will inform you when its done

**Comment by Sasukezynho** [comment]
thx u Alien, u the best

**Comment by KaizenTzy** [comment]
still error ..
